### PR TITLE
Improve output for data constructors

### LINKED ISSUE #54: Improve output for data/newtype constructors on REPL interface
Currently, the REPL interface only shows the names of constructors for `data`/`newtype` declarations like so:
```hs
Tuple

tuples                                   Data.Tuple
```

```hs
Additive

prelude                                  Data.Monoid.Additive
```

I think this can be improved by adding `data constructor` and `newtype constructor` prefixes. I'm also currently trying to integrate `docs-search` into Emacs and having prefixes like this would make it easier to write, considering the output format itself is already easy to parse given how the results are spaced.
```hs
data constructor Tuple :: a -> b -> Tuple a b

tuples                                   Data.Tuple
```

```hs
newtype constructor Additive :: a -> Additive a

prelude                                  Data.Monoid.Additive
```

Any thoughts? ~~I can try working on this later this week as well.~~ I have a working implementation at PureFunctor@1518f71

### PR DESCRIPTION
**Pull request by purefunctor**
Fixes #54.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
CI is failing because the package set needs to be bumped to `0.15.0`.

**Comment by purefunctor** [comment]
I'll try updating the application to 0.15.0 today as well.

**Comment by klntsky** [comment]
@PureFunctor no need to, I have it almost done in my stash. I am slowly working on updating dependencies.

Also this: https://github.com/rnons/purescript-html-parser-halogen/pull/16

**Comment by klntsky** [comment]
I'm going to take over this PR and merge soon

**Pull request merged**
