### PR TITLE
Changes for v0.0.5 [WIP]

### PR DESCRIPTION
**Pull request by klntsky**
Working on: #15, #16.

### CODE REVIEW

**Comment by f-f** [comment]
@klntsky can this be merged already?

**Comment by klntsky** [comment]
Nope, sorry.

**Comment by klntsky** [comment]
I am going to add correct sorting for packages and declarations (packages should appear first), and also sorting by popularity.

**Comment by f-f** [comment]
Cool! Though what I meant above was "is there something obviously broken that would prevent this stuff from being in `master`? (i.e. we can always have another PR for new things)

**Pull request merged**
